version: '3.8'

services:
  # frontend-todo:
  #   image: todo-frontend
  #   build: ./frontend/todo
  #   ports:
  #     - "3001:3000"
  #   depends_on:
  #     - frontend-chatapp   
  #   container_name: todo-frontend
  #   networks:
  #     - freeapi-internal  

  frontend-chatapp:
    image: chatapp-frontend
    build: ./frontend/chat-app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    container_name: chatapp-frontend
    networks:
      - freeapi-internal

  backend:
    image: freeapi-backend
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/freeapi
      - /usr/src/freeapi/node_modules
    depends_on:
      - mongodb
    env_file:
      - ./.env
    container_name: freeapi-backend
    networks:
      - freeapi-internal
    

  mongodb:
    image: mongo
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"
    container_name: freeapi-mongodb
    networks:
      - freeapi-internal

networks:
  freeapi-internal:

volumes:
  db-data:
