apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-app
      tier: backend
  template:
    metadata:
      labels:
      app: chat-app
      tier: backend
    spec:
      containers:
      - name: chat-app-backend
        image: <image-name:tag>  # update the backend image from dockerhub
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: MONGO_MEMORY_SERVER_PORT
          value: "10000"
        - name: MONGODB_URI
          value: "mongodb/path"
        - name: NODE_ENV
          value: "development"
        - name: EXPRESS_SESSION_SECRET
          value: "7fdOMCFRSLD9cv1k-5n3Dz5n3DmVmVHVIg9GG_OGTUkBfLNdgZAwKDNtoCJ0X0cyqaM0ogR80-zh9kx0Mkx"
        - name: ACCESS_TOKEN_SECRET
          value: "LD9cv1kBfgRHVIg9GG_OGzh9TUkcyqgZAaM0o3DmVkx08MCFRSzMocyO3UtNdDNtoCJ0X0-5nLwK7fdO"
        - name: ACCESS_TOKEN_EXPIRY
          value: "1d"
        - name: REFRESH_TOKEN_SECRET
          value: "CMdDNtowK7fX0-5D9cv0oJ008MCFRSLHVTUkcyqgZAaIg9GG_OGzh9zMocyO3UtN1kBfLRn3DmVkxdO"
        - name: REFRESH_TOKEN_EXPIRY
          value: "10d"
        - name: CORS_ORIGIN
          value: "https://<frontend-FQDN>"   # update the frontend url as http or https to resolve the cors issue
        - name: FREEAPI_HOST_URL
          value: "https://<backend-FQDN>"  # update the backend url as http or https 

