apiVersion: v1
kind: Service
metadata:
  name: chat-app-backend-svc
spec:
  selector:
    app: chat-app
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32000  # Specify your desired static NodePort here
  type: NodePort

##### BELOW IS USED When using ingress as ALB LoadBalancer ##############

# apiVersion: v1
# kind: Service
# metadata:
#   name: freeapi-service
# spec:
#   selector:
#     app: freeapi
#   ports:
#     - protocol: TCP
#       port: 8080
#       targetPort: 8080
#   type: LoadBalancer # or NodePort depending on your requirements



