apiVersion: v1
kind: Service
metadata:
  name: chat-app-frontend-svc
spec:
  selector:
    app: chat-app-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32001  # Specify your desired static NodePort here
  type: NodePort

